version: "3.9"

services:
  mkmClient_db_local:
    image: postgres
    container_name: mkmClient_db_local
    networks:
      app_net:
        ipv4_address: 172.16.100.10
    ports:
      - 5432:5432
    env_file:
      - postgres/database.env
    volumes:
      - mkm-database-data:/var/lib/postgresql/data/
  mkmClient-BE:
    image: mkmclient/be:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      app_net:
        ipv4_address: 172.16.100.20
    ports:
      - 8081:8081


volumes:
  mkm-database-data:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1